group :server do
  guard 'process', name: 'dev_server', command: 'rake server' do
    watch(%r{^lib/})
  end
end

group :test do
  guard 'rspec', all_on_start: true, cli: "--color --format Fuubar" do
    watch(%r{^spec/.+_spec\.rb})
    watch(%r{^lib/(.+)\.rb}) { |m| "spec/#{m[1]}_spec.rb" }

    watch('spec/spec_helper.rb') { "spec" }
    watch(%r{spec/support/(.+)\.rb}) { "spec" }
  end
end
