$LOAD_PATH.unshift(File.expand_path(Dir.pwd + "/lib"))

guard 'process', name: 'dev_server', command: 'rake server' do
  watch(%r{^lib/})
end

guard 'rspec', spec_paths: "spec", cli: "--color --format Fuubar" do
  watch(%r{^spec/.+_spec\.rb})
  watch(%r{^lib/(.+)\.rb}) { |m| "spec/#{m[1]}_spec.rb" }

  watch('spec/spec_helper.rb') { "spec" }
  watch(%r{spec/support/(.+)\.rb}) { "spec" }
end
